import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Navbar } from '@/components/navbar';
import { Providers } from './providers';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className="mx-auto max-w-5xl px-6">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
