import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import { Navbar, NavbarContent, NavbarItem } from '@nextui-org/navbar';

import { ThemeToggle } from '@/components/theme-toggle';

import { Providers } from './providers';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Navbar>
            <NavbarContent>
              <NavbarItem>
                <Link href="/">Home</Link>
              </NavbarItem>

              <NavbarItem>
                <Link href="/blog">Blog</Link>
              </NavbarItem>

              <NavbarItem>
                <Link href="/projects">Projects</Link>
              </NavbarItem>
            </NavbarContent>

            <NavbarContent justify="end">
              <NavbarItem>
                <ThemeToggle />
              </NavbarItem>
            </NavbarContent>
          </Navbar>

          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
